services:
  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile

  buildingblocks:
    image: buildingblocks
    build:
      context: .
      dockerfile: BuildingBlocks/BuildingBlocks/Dockerfile

